[package]
name = "aster"
version = "0.4.9"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A libsyntax ast builder"
repository = "https://github.com/erickt/rust-aster"

[features]
with-syntex = ["syntex_syntax"]

[dependencies]
syntex_syntax = { version = ">= 0.16.0", optional = true }

[[test]]
name = "test"
path = "tests/test.rs"
